# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, manifest-v3 ]
  pull_request:
    branches: [ main, manifest-v3 ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [15.x, 16.x, 17.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload build-chrome artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-chrome ${{ matrix.node-version }} ${{ matrix.os }}
        path: build-chrome
    - name: Upload build-firefox artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-firefox ${{ matrix.node-version }} ${{ matrix.os }}
        path: build-firefox
    - name: Upload build-web artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-web ${{ matrix.node-version }} ${{ matrix.os }}
        path: build-web
