# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [21.x, 22.x]
        include:
          - os: ubuntu-latest
            node-version: 17.x

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Upload build-chrome artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-chrome ${{ matrix.node-version }} ${{ matrix.os }}
        path: build-chrome
    - name: Upload build-firefox artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-firefox ${{ matrix.node-version }} ${{ matrix.os }}
        path: build-firefox
